name: Continous integeration

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2             #checkout repo to working dir
        name: Checkout repo

      - uses: docker/setup-buildx-action@v3   #Setup QEMU, builds image compatible w multiple platforms
        name: Setup QEMU

      - uses: docker/setup-buildx-action@v3   #Buildx for building docker images
        name: Setup docker Buildx

      - uses: docker/build-push-action@v2     #Build images on push
        name: Build and Export Docker Image
        with:
          context: .
          file: ./Dockerfile
          push: false                         #to push to dockerhub
          load: true                          #to docker runtime
          tags: |
            yt-downloader:latest
          outputs: type=Docker,dest=/temp/yt-downloader.tar

      - name: Upload Docker
        uses: actions/upload-artifact@v4
        with:
          name: yt-downloader
          path: /temp/yt-downloader.tar

      - run: docker images
        name: Display docker images

  test:
    name: Functionality Check
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: yt-downloader
          path: /temp/

      - name: Load Docker Image
        run:  |
          docker load --input /temp/yt-downloader.tar

      - name: Run tests within docker container
        run:  |
          docker run --rm yt-downloader pytest