name: Continous integeration

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2             #checkout repo to working dir
        name: Checkout repo

      - uses: docker/setup-buildx-action@v3   #Setup QEMU, builds image compatible w multiple platforms
        name: Setup QEMU

      - uses: docker/setup-buildx-action@v3   #Buildx for building docker images
        name: Setup docker Buildx

      - uses: docker/build-push-action@v2     #Build images on push
        name: Build Docker Image
        with:
          context: .
          file: ./Dockerfile
          push: false                         #to push to dockerhub
          load: true                          #to temporarily store
          tags: |
            hello-world:latest
      - run: docker images
        name: Display docker images

  test:
    name: Functionality Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Runs Tests
        run: |
          source venv/bin/activate
          docker run --rm -d --name test-container hello-world:latest
          pytest