name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: docker/setup-buildx-action@v3
        name: Setup QEMU

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker Buildx

      - name: Build and Save Docker Image
        run: |
          docker build -t yt-downloader .
          mkdir -p temp/
          docker save yt-downloader > temp/yt-downloader.tar

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: yt-downloader
          path: temp/yt-downloader.tar

      - run: docker images
        name: Display Docker Images

  test:
    name: Functionality Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: yt-downloader
          path: temp/

      - name: Load Docker Image
        run: |
          docker load --input temp/yt-downloader.tar

      - name: Run Tests within Docker Container
        run: |
          docker run --rm yt-downloader pytest
