name: Continous integeration

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo

      - uses: docker/setup-buildx-action@v3
        name: Setup QEMU

      - uses: docker/setup-buildx-action@v3
        name: Setup docker Buildx

      - uses: docker/build-push-action@v2
        name: Build Docker Image
        with:
          context:  .
          file: ./Dockerfile
          push: false
          load: true
          tags: |
            hello-world:latest
      - run: docker images
        name: Display docker images